FROM node:18-alpine AS build
RUN apk upgrade --available
RUN mkdir -p /usr/app
COPY umbrella-insurance-react-ui/public /usr/app/public
COPY umbrella-insurance-react-ui/src /usr/app/src
COPY umbrella-insurance-react-ui/package.json /usr/app/package.json
COPY umbrella-insurance-react-ui/tsconfig.json /usr/app/tsconfig.json
WORKDIR /usr/app
# Declaring env
ENV NODE_ENV=production
ENV REACT_APP_DOMAIN=https://www.umbrella-insurance.co
ENV REACT_APP_WS_DOMAIN=www.umbrella-insurance.co
ENV REACT_APP_WS_PROTOCOL=wss
ENV REACT_APP_VERSION=0.1.2
ENV REACT_APP_NAME=umbrella-insurance-react-ui
RUN npm update
RUN npm install
RUN npm run build
#RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache
#RUN addgroup -S spring && adduser -S spring -G spring
#USER spring:spring
FROM nginx:1.23.1-alpine
ENV NODE_ENV=production
ENV REACT_APP_DOMAIN=https://www.umbrella-insurance.co
ENV REACT_APP_WS_DOMAIN=www.umbrella-insurance.co
ENV REACT_APP_WS_PROTOCOL=wss
ENV REACT_APP_VERSION=0.1.2
ENV REACT_APP_NAME=umbrella-insurance-react-ui
EXPOSE 80
COPY ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/build /usr/share/nginx/html