CREATE TABLE IF NOT EXISTS public.cities (
    city_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    city_name varchar NULL,
    CONSTRAINT cities_pk PRIMARY KEY (city_id),
    CONSTRAINT cities_un UNIQUE (city_name)
);