CREATE TABLE IF NOT EXISTS public.islands (
    island_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    island_name varchar NOT NULL,
    CONSTRAINT islands_pk PRIMARY KEY (island_id),
    CONSTRAINT islands_un UNIQUE (island_name)
);