INSERT INTO public.cities (city_name) VALUES ('Pittsburgh');
INSERT INTO public.cities (city_name) VALUES ('Paradise');
INSERT INTO public.cities (city_name) VALUES ('Kansas City');
INSERT INTO public.cities (city_name) VALUES ('Arlington');
INSERT INTO public.cities (city_name) VALUES ('Charlotte');
INSERT INTO public.cities (city_name) VALUES ('New Orleans');
INSERT INTO public.cities (city_name) VALUES ('Denver');
INSERT INTO public.cities (city_name) VALUES ('Jacksonville');
INSERT INTO public.cities (city_name) VALUES ('Detroit');
INSERT INTO public.cities (city_name) VALUES ('Foxborough');
INSERT INTO public.cities (city_name) VALUES ('Miami Gardens');
INSERT INTO public.cities (city_name) VALUES ('Orchard Park');
INSERT INTO public.cities (city_name) VALUES ('Cleveland');
INSERT INTO public.cities (city_name) VALUES ('Green Bay');
INSERT INTO public.cities (city_name) VALUES ('Santa Clara');
INSERT INTO public.cities (city_name) VALUES ('Philadelphia');
INSERT INTO public.cities (city_name) VALUES ('Indianapolis');
INSERT INTO public.cities (city_name) VALUES ('Seattle');
INSERT INTO public.cities (city_name) VALUES ('Baltimore');
INSERT INTO public.cities (city_name) VALUES ('Atlanta');
INSERT INTO public.cities (city_name) VALUES ('East Rutherford');
INSERT INTO public.cities (city_name) VALUES ('Nashville');
INSERT INTO public.cities (city_name) VALUES ('Landover');
INSERT INTO public.cities (city_name) VALUES ('Houston');
INSERT INTO public.cities (city_name) VALUES ('Cincinnati');
INSERT INTO public.cities (city_name) VALUES ('Tampa');
INSERT INTO public.cities (city_name) VALUES ('Inglewood');
INSERT INTO public.cities (city_name) VALUES ('Chicago');
INSERT INTO public.cities (city_name) VALUES ('Glendale');
INSERT INTO public.cities (city_name) VALUES ('Minneapolis');
