INSERT INTO public.countries (country_name) VALUES ('Afghanistan');
INSERT INTO public.countries (country_name) VALUES ('Albania');
INSERT INTO public.countries (country_name) VALUES ('Algeria');
INSERT INTO public.countries (country_name) VALUES ('Antigua and Barbuda');
INSERT INTO public.countries (country_name) VALUES ('Argentina');
INSERT INTO public.countries (country_name) VALUES ('Armenia');
INSERT INTO public.countries (country_name) VALUES ('Australia');
INSERT INTO public.countries (country_name) VALUES ('Austria');
INSERT INTO public.countries (country_name) VALUES ('Azerbaijan');
INSERT INTO public.countries (country_name) VALUES ('Azores');
INSERT INTO public.countries (country_name) VALUES ('Bahamas');
INSERT INTO public.countries (country_name) VALUES ('Bangladesh');
INSERT INTO public.countries (country_name) VALUES ('Barbados');
INSERT INTO public.countries (country_name) VALUES ('Belarus');
INSERT INTO public.countries (country_name) VALUES ('Belgium');
INSERT INTO public.countries (country_name) VALUES ('Belize');
INSERT INTO public.countries (country_name) VALUES ('Bermuda');
INSERT INTO public.countries (country_name) VALUES ('Bolivia');
INSERT INTO public.countries (country_name) VALUES ('Bosnia and Herzegovina');
INSERT INTO public.countries (country_name) VALUES ('Brazil');
INSERT INTO public.countries (country_name) VALUES ('Bulgaria');
INSERT INTO public.countries (country_name) VALUES ('Cambodia');
INSERT INTO public.countries (country_name) VALUES ('Cameroon');
INSERT INTO public.countries (country_name) VALUES ('Canada');
INSERT INTO public.countries (country_name) VALUES ('Cape Verde');
INSERT INTO public.countries (country_name) VALUES ('Chile');
INSERT INTO public.countries (country_name) VALUES ('China');
INSERT INTO public.countries (country_name) VALUES ('Columbia');
INSERT INTO public.countries (country_name) VALUES ('Costa Rica');
INSERT INTO public.countries (country_name) VALUES ('Croatia');
INSERT INTO public.countries (country_name) VALUES ('Cuba');
INSERT INTO public.countries (country_name) VALUES ('Cyprus');
INSERT INTO public.countries (country_name) VALUES ('Czech Republic');
INSERT INTO public.countries (country_name) VALUES ('Czechoslovakia');
INSERT INTO public.countries (country_name) VALUES ('Denmark');
INSERT INTO public.countries (country_name) VALUES ('Dominica');
INSERT INTO public.countries (country_name) VALUES ('Dominican Republic');
INSERT INTO public.countries (country_name) VALUES ('Ecuador');
INSERT INTO public.countries (country_name) VALUES ('Egypt');
INSERT INTO public.countries (country_name) VALUES ('El Salvador');
INSERT INTO public.countries (country_name) VALUES ('England');
INSERT INTO public.countries (country_name) VALUES ('Eritrea');
INSERT INTO public.countries (country_name) VALUES ('Ethiopia');
INSERT INTO public.countries (country_name) VALUES ('Fiji');
INSERT INTO public.countries (country_name) VALUES ('Finland');
INSERT INTO public.countries (country_name) VALUES ('France');
INSERT INTO public.countries (country_name) VALUES ('Georgia');
INSERT INTO public.countries (country_name) VALUES ('Germany');
INSERT INTO public.countries (country_name) VALUES ('Ghana');
INSERT INTO public.countries (country_name) VALUES ('Greece');
INSERT INTO public.countries (country_name) VALUES ('Grenada');
INSERT INTO public.countries (country_name) VALUES ('Guam');
INSERT INTO public.countries (country_name) VALUES ('Guatemala');
INSERT INTO public.countries (country_name) VALUES ('Guyana');
INSERT INTO public.countries (country_name) VALUES ('Haiti');
INSERT INTO public.countries (country_name) VALUES ('Honduras');
INSERT INTO public.countries (country_name) VALUES ('Hong Kong');
INSERT INTO public.countries (country_name) VALUES ('Hungary');
INSERT INTO public.countries (country_name) VALUES ('India');
INSERT INTO public.countries (country_name) VALUES ('Indonesia');
INSERT INTO public.countries (country_name) VALUES ('Iran');
INSERT INTO public.countries (country_name) VALUES ('Iraq');
INSERT INTO public.countries (country_name) VALUES ('Ireland');
INSERT INTO public.countries (country_name) VALUES ('Israel');
INSERT INTO public.countries (country_name) VALUES ('Italy');
INSERT INTO public.countries (country_name) VALUES ('Jamaica');
INSERT INTO public.countries (country_name) VALUES ('Japan');
INSERT INTO public.countries (country_name) VALUES ('Jordan');
INSERT INTO public.countries (country_name) VALUES ('Kenya');
INSERT INTO public.countries (country_name) VALUES ('Korea');
INSERT INTO public.countries (country_name) VALUES ('Kosovo');
INSERT INTO public.countries (country_name) VALUES ('Kuwait');
INSERT INTO public.countries (country_name) VALUES ('Laos');
INSERT INTO public.countries (country_name) VALUES ('Latvia');
INSERT INTO public.countries (country_name) VALUES ('Lebanon');
INSERT INTO public.countries (country_name) VALUES ('Liberia');
INSERT INTO public.countries (country_name) VALUES ('Lithuania');
INSERT INTO public.countries (country_name) VALUES ('Macedonia');
INSERT INTO public.countries (country_name) VALUES ('Malaysia');
INSERT INTO public.countries (country_name) VALUES ('Mexico');
INSERT INTO public.countries (country_name) VALUES ('Moldova');
INSERT INTO public.countries (country_name) VALUES ('Morocco');
INSERT INTO public.countries (country_name) VALUES ('Myanmar');
INSERT INTO public.countries (country_name) VALUES ('Nepal');
INSERT INTO public.countries (country_name) VALUES ('Netherlands');
INSERT INTO public.countries (country_name) VALUES ('New Zealand');
INSERT INTO public.countries (country_name) VALUES ('Nicaragua');
INSERT INTO public.countries (country_name) VALUES ('Nigeria');
INSERT INTO public.countries (country_name) VALUES ('Northern Ireland');
INSERT INTO public.countries (country_name) VALUES ('Norway');
INSERT INTO public.countries (country_name) VALUES ('Other US Island Areas');
INSERT INTO public.countries (country_name) VALUES ('Pakistan');
INSERT INTO public.countries (country_name) VALUES ('Panama');
INSERT INTO public.countries (country_name) VALUES ('Paraguay');
INSERT INTO public.countries (country_name) VALUES ('Peru');
INSERT INTO public.countries (country_name) VALUES ('Philippines');
INSERT INTO public.countries (country_name) VALUES ('Poland');
INSERT INTO public.countries (country_name) VALUES ('Portugal');
INSERT INTO public.countries (country_name) VALUES ('Puerto Rico');
INSERT INTO public.countries (country_name) VALUES ('Romania');
INSERT INTO public.countries (country_name) VALUES ('Russia');
INSERT INTO public.countries (country_name) VALUES ('Samoa');
INSERT INTO public.countries (country_name) VALUES ('Saudi Arabia');
INSERT INTO public.countries (country_name) VALUES ('Scotland');
INSERT INTO public.countries (country_name) VALUES ('Senegal');
INSERT INTO public.countries (country_name) VALUES ('Serbia');
INSERT INTO public.countries (country_name) VALUES ('Sierra Leone');
INSERT INTO public.countries (country_name) VALUES ('Singapore');
INSERT INTO public.countries (country_name) VALUES ('Slovakia');
INSERT INTO public.countries (country_name) VALUES ('Somalia');
INSERT INTO public.countries (country_name) VALUES ('South Africa');
INSERT INTO public.countries (country_name) VALUES ('South Korea');
INSERT INTO public.countries (country_name) VALUES ('Spain');
INSERT INTO public.countries (country_name) VALUES ('Sri Lanka');
INSERT INTO public.countries (country_name) VALUES ('St Kitts Nevis');
INSERT INTO public.countries (country_name) VALUES ('St Lucia');
INSERT INTO public.countries (country_name) VALUES ('St Vincent and the Grenadines');
INSERT INTO public.countries (country_name) VALUES ('Sudan');
INSERT INTO public.countries (country_name) VALUES ('Sweden');
INSERT INTO public.countries (country_name) VALUES ('Switzerland');
INSERT INTO public.countries (country_name) VALUES ('Syria');
INSERT INTO public.countries (country_name) VALUES ('Taiwan');
INSERT INTO public.countries (country_name) VALUES ('Tanzania');
INSERT INTO public.countries (country_name) VALUES ('Thailand');
INSERT INTO public.countries (country_name) VALUES ('Tonga');
INSERT INTO public.countries (country_name) VALUES ('Trinidad and Tobago');
INSERT INTO public.countries (country_name) VALUES ('Turkey');
INSERT INTO public.countries (country_name) VALUES ('US Virgin Islands');
INSERT INTO public.countries (country_name) VALUES ('Uganda');
INSERT INTO public.countries (country_name) VALUES ('Ukraine');
INSERT INTO public.countries (country_name) VALUES ('United Kingdom');
INSERT INTO public.countries (country_name) VALUES ('United States');
INSERT INTO public.countries (country_name) VALUES ('Uruguay');
INSERT INTO public.countries (country_name) VALUES ('USSR');
INSERT INTO public.countries (country_name) VALUES ('Uzbekistan');
INSERT INTO public.countries (country_name) VALUES ('Venezuela');
INSERT INTO public.countries (country_name) VALUES ('Vietnam');
INSERT INTO public.countries (country_name) VALUES ('Wales');
INSERT INTO public.countries (country_name) VALUES ('Yemen');
INSERT INTO public.countries (country_name) VALUES ('Yugoslavia');
INSERT INTO public.countries (country_name) VALUES ('Zimbabwe');
