INSERT INTO public.game_types (game_type_name) VALUES ('Baseball');
INSERT INTO public.game_types (game_type_name) VALUES ('Basketball');
INSERT INTO public.game_types (game_type_name) VALUES ('Cricket');
INSERT INTO public.game_types (game_type_name) VALUES ('Football');
INSERT INTO public.game_types (game_type_name) VALUES ('Golf');
INSERT INTO public.game_types (game_type_name) VALUES ('Hockey');
INSERT INTO public.game_types (game_type_name) VALUES ('Rugby');
INSERT INTO public.game_types (game_type_name) VALUES ('Soccer');
INSERT INTO public.game_types (game_type_name) VALUES ('Table Tennis');
INSERT INTO public.game_types (game_type_name) VALUES ('Tennis');
INSERT INTO public.game_types (game_type_name) VALUES ('Volleyball');
