CREATE TABLE IF NOT EXISTS public.states (
    state_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    state_name varchar NOT NULL,
    CONSTRAINT states_pk PRIMARY KEY (state_id)
);