INSERT INTO public.states (state_name) VALUES ('Alabama');
INSERT INTO public.states (state_name) VALUES ('Alaska');
INSERT INTO public.states (state_name) VALUES ('Arizona');
INSERT INTO public.states (state_name) VALUES ('Arkansas');
INSERT INTO public.states (state_name) VALUES ('California');
INSERT INTO public.states (state_name) VALUES ('Colorado');
INSERT INTO public.states (state_name) VALUES ('Connecticut');
INSERT INTO public.states (state_name) VALUES ('Delaware');
INSERT INTO public.states (state_name) VALUES ('Florida');
INSERT INTO public.states (state_name) VALUES ('Georgia');
INSERT INTO public.states (state_name) VALUES ('Hawaii');
INSERT INTO public.states (state_name) VALUES ('Idaho');
INSERT INTO public.states (state_name) VALUES ('Illinois');
INSERT INTO public.states (state_name) VALUES ('Indiana');
INSERT INTO public.states (state_name) VALUES ('Iowa');
INSERT INTO public.states (state_name) VALUES ('Kansas');
INSERT INTO public.states (state_name) VALUES ('Kentucky');
INSERT INTO public.states (state_name) VALUES ('Louisiana');
INSERT INTO public.states (state_name) VALUES ('Maine');
INSERT INTO public.states (state_name) VALUES ('Maryland');
INSERT INTO public.states (state_name) VALUES ('Massachusetts');
INSERT INTO public.states (state_name) VALUES ('Michigan');
INSERT INTO public.states (state_name) VALUES ('Minnesota');
INSERT INTO public.states (state_name) VALUES ('Mississippi');
INSERT INTO public.states (state_name) VALUES ('Missouri');
INSERT INTO public.states (state_name) VALUES ('Montana');
INSERT INTO public.states (state_name) VALUES ('Nebraska');
INSERT INTO public.states (state_name) VALUES ('Nevada');
INSERT INTO public.states (state_name) VALUES ('New Hampshire');
INSERT INTO public.states (state_name) VALUES ('New Jersey');
INSERT INTO public.states (state_name) VALUES ('New Mexico');
INSERT INTO public.states (state_name) VALUES ('New York');
INSERT INTO public.states (state_name) VALUES ('North Carolina');
INSERT INTO public.states (state_name) VALUES ('North Dakota');
INSERT INTO public.states (state_name) VALUES ('Ohio');
INSERT INTO public.states (state_name) VALUES ('Oklahoma');
INSERT INTO public.states (state_name) VALUES ('Oregon');
INSERT INTO public.states (state_name) VALUES ('Pennsylvania');
INSERT INTO public.states (state_name) VALUES ('Rhode Island');
INSERT INTO public.states (state_name) VALUES ('South Carolina');
INSERT INTO public.states (state_name) VALUES ('South Dakota');
INSERT INTO public.states (state_name) VALUES ('Tennessee');
INSERT INTO public.states (state_name) VALUES ('Texas');
INSERT INTO public.states (state_name) VALUES ('Utah');
INSERT INTO public.states (state_name) VALUES ('Vermont');
INSERT INTO public.states (state_name) VALUES ('Virginia');
INSERT INTO public.states (state_name) VALUES ('Washington');
INSERT INTO public.states (state_name) VALUES ('West Virginia');
INSERT INTO public.states (state_name) VALUES ('Wisconsin');
INSERT INTO public.states (state_name) VALUES ('Wyoming');
