CREATE TABLE IF NOT EXISTS public.zip_codes (
    zip_code_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    zip_code_value varchar NOT NULL,
    CONSTRAINT zip_codes_pk PRIMARY KEY (zip_code_id)
);