CREATE TABLE IF NOT EXISTS public.carts (
    cart_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    stage varchar NOT NULL,
    user_id int8 NULL,
    created_date_time timestamp NOT NULL,
    CONSTRAINT carts_pk PRIMARY KEY (cart_id)
);