CREATE TABLE IF NOT EXISTS public.referees (
    referee_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    person_id int8 NULL,
    CONSTRAINT referees_pk PRIMARY KEY (referee_id)
);