CREATE TABLE IF NOT EXISTS public.schedules (
    schedule_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    season_id int8 NULL,
    game_id int8 NULL,
    CONSTRAINT schedules_pk PRIMARY KEY (schedule_id)
);