CREATE TABLE IF NOT EXISTS public.football_player_stats (
    football_player_stats_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    game_id int8 NULL,
    player_id int8 NULL,
    total_tackles int8 NULL,
    solo_tackles int8 NULL,
    total_sacks int8 NULL,
    tackles_for_loss int8 NULL,
    passes_defended int8 NULL,
    quarterback_hits int8 NULL,
    defensive_touchdowns int8 NULL,
    total_fumbles int8 NULL,
    fumbles_lost int8 NULL,
    fumbles_recovered int8 NULL,
    interceptions int8 NULL,
    interception_yards int8 NULL,
    interception_touchdowns int8 NULL,
    number_of_field_goals int8 NULL,
    field_goal_percentage int8 NULL,
    longest_field_goal int8 NULL,
    extra_points int8 NULL,
    extra_point_attempts int8 NULL,
    points int8 NULL,
    number_of_kick_returns int8 NULL,
    total_kick_return_yards int8 NULL,
    number_of_yards_per_kick_return double precision NULL,
    longest_kick_return_yards int8 NULL,
    kick_return_touchdowns int8 NULL,
    completions int8 NULL,
    passing_attempts int8 NULL,
    passing_yards int8 NULL,
    yards_per_pass_attempt double precision NULL,
    passing_touchdowns int8 NULL,
    interceptions_thrown int8 NULL,
    number_of_times_sacked int8 NULL,
    sacked_yards_lost int8 NULL,
    passer_rating double precision NULL,
    adjusted_qbr double precision NULL,
    number_of_punts int8 NULL,
    total_punt_yards int8 NULL,
    punt_yards_per_punt double precision NULL,
    touchbacks int8 NULL,
    in20 int8 NULL,
    longest_punt_yards int8 NULL,
    number_of_punt_returns int8 NULL,
    total_punt_return_yards int8 NULL,
    punt_return_yards_per_punt_return double precision NULL,
    longest_punt_return_yards int8 NULL,
    punt_return_touchdowns int8 NULL,
    total_receptions int8 NULL,
    total_receiving_yards int8 NULL,
    average_yards_per_reception double precision NULL,
    receiving_touchdowns int8 NULL,
    longest_reception int8 NULL,
    receiving_targets int8 NULL,
    rushing_attempts int8 NULL,
    averages double precision NULL,
    rushing_touchdowns int8 NULL,
    longest_run int8 NULL,
    CONSTRAINT football_player_stats_pk PRIMARY KEY (football_player_stats_id)
);