CREATE TABLE IF NOT EXISTS public.stats (
    stat_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    stat_name varchar NOT NULL,
    CONSTRAINT stats_pk PRIMARY KEY (stat_id),
    CONSTRAINT stats_name_unique UNIQUE (stat_name)
);