CREATE TABLE IF NOT EXISTS public.trophies (
    trophy_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    trophy_name varchar NOT NULL,
    CONSTRAINT trophies_pk PRIMARY KEY (trophy_id),
    CONSTRAINT trophies_unique UNIQUE (trophy_name)
);