CREATE TABLE IF NOT EXISTS public.pending_bets (
    pending_bet_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    session_id int8 NULL,
    game_id int8 NULL,
    minimum_odds double precision NOT NULL,
    maximum_wager_amount double precision NOT NULL,
    created_date_time timestamp NOT NULL,
    unit_id int8 NULL,
    bot_id int8 NULL,
    is_bot_bet bool NULL,
    is_charity_bet bool NULL,
    charity_id int8 NULL,
    pending_bet_state_id int8 NULL,
    fee_id int8 NULL,
    pending_bet_name varchar NOT NULL,
    split_pending_bet_id_1 int8 NULL,
    split_pending_bet_id_2 int8 NULL,
    original_pending_bet_id int8 NULL,
    account_balance_escrow_transaction_id int8 NULL,
    account_balance_canceled_escrow_transaction_id int8 NULL,
    canceled_date_time timestamp NULL,
    bet_type_id int8 NULL,
    order_type_id int8 NULL,
    CONSTRAINT pending_bets_pk PRIMARY KEY (pending_bet_id),
    CONSTRAINT pending_bets_unique UNIQUE (pending_bet_name)
);