CREATE TABLE IF NOT EXISTS public.pending_policies (
    pending_policy_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    premium_amount double precision NULL,
    location_id int8 NULL,
    coverage_amount double precision NULL,
    implied_probability double precision NULL,
    unit_id int8 NULL,
    peril_id int8 NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    pending_policy_state_id int8 NULL,
    session_id int8 NULL,
    fee_id int8 NULL,
    pending_policy_name varchar NOT NULL,
    split_pending_policy_id_1 int8 NULL,
    split_pending_policy_id_2 int8 NULL,
    original_pending_policy_id int8 NULL,
    account_balance_escrow_transaction_id int8 NULL,
    account_balance_canceled_escrow_transaction_id int8 NULL,
    created_date_time timestamp NOT NULL,
    canceled_date_time timestamp NULL,
    pending_policy_type_id int8 NULL,
    order_type_id int8 NULL,
    CONSTRAINT pending_policies_pk PRIMARY KEY (pending_policy_id),
    CONSTRAINT pending_policies_unique UNIQUE (pending_policy_name)
);